### ISSUE TITLE
Add additional decorations

### ISSUE THREAD

**Issue by ishovkun** [andreyorst/Breezemite#1]
Thank you for the decorations: they look fantastic.
The thing, however, is that such decorations as "always on top" or "pin to all desktops" are not drawn with Breezemite decoration theme. I know, the don't exist in OSX, but I still find them very useful. Could you imlement then as well as, let's say, circles of various colors?

**Comment by miguelmartin75** [comment]
:+1: this would be good

**Comment by andreyorst** [comment]
@ishovkun  if I will come with any idea about this buttons i'll do it asap. Also I've found some other issues, and i think i need to fix them first and after it I will think about the way buttons can be done.

**Comment by andreyorst** [comment]
@ishovkun, done.
