### ISSUE TITLE
Shade button doesn't appears

### ISSUE THREAD

**Issue by GrayJack** [andreyorst/Breezemite#10]
![screenshot_20170710_060916](https://user-images.githubusercontent.com/17973728/28010777-5fa3aece-6536-11e7-9bc9-e70c69cd4152.png)

As you can see above, the Shade button is configured and applied and yet, it doesn't show in the window bar. 

Easily fixable removing the "." at the start of the ".shade.svg".

Once done, and I use shade, I get a this bug:
![screenshot_20170710_062202](https://user-images.githubusercontent.com/17973728/28011431-b7cd0f3a-6538-11e7-8879-12c99a7d8745.png)

**Comment by andreyorst** [comment]
#7
![image](https://user-images.githubusercontent.com/19470159/28023915-ed494066-6597-11e7-9311-15a2b0048f9a.png)
