### ISSUE TITLE
Windows Borders Problem

### ISSUE THREAD

**Issue by TalhaEryasar** [andreyorst/Breezemite#11]
When I apply the brezeemite theme side of the window borders doesn't seen and I couldn't fix this problem can anyone help?

![screenshot_20170905_014527](https://user-images.githubusercontent.com/25838936/30039584-cac104d2-91c2-11e7-9a45-52d199b0205b.png)

**Comment by andreyorst** [comment]
Looks like #9.
What DPI do you use?

**Comment by TalhaEryasar** [comment]
1920x1080

5 Eyl 2017 Sal, saat 12:46 tarihinde Andrey Orst <notifications@github.com>
şunu yazdı:

**Comment by andreyorst** [comment]
Yeah 1920x1080 is your resolution. But what DPI is your display?
Try to set `custom DPI = 96` in your Settings > Fonts and logout, then log back in

**Comment by TalhaEryasar** [comment]
Yes it's done. Thank you very much i can use the theme right now and i like
it more when using:D

Thanks for the theme and your helps again..

2017-09-05 12:16 GMT+00:00 Andrey Orst <notifications@github.com>:

**Comment by andreyorst** [comment]
Seems like your DPI is not 96 and setting it to 96 may fix the theme, but also may break the fonts. Try to figure out DPI of your screen and post it here, i'll tweak theme for your paticular display

**Comment by TalhaEryasar** [comment]
Yes. I change the dpi settings to 96 and it's fixed but my fonts changed
too. My font size was 12 but I use 10 now and there is no problem it's okey
thanks👍🏻✌🏻

5 Eyl 2017 Sal, saat 16:29 tarihinde Andrey Orst <notifications@github.com>
şunu yazdı:

**Comment by tjohnman** [comment]
Can this be worked around somehow? I love this theme but I also want to force a higher DPI.

**Comment by andreyorst** [comment]
@tjohnman post your DPI value and fonts here, I'll try to tweak theme for your particular settings

**Comment by tjohnman** [comment]
I distro-hop a lot and wouldn't want to give you extra work for something I might or might not use. In fact I'm using a different setup now (GTK).

My DPI was 120 and the font was Lato. But I insist, no need to go out of your way.
