### ISSUE TITLE
1px transparent border

### ISSUE THREAD

**Issue by re1** [andreyorst/Breezemite#13]
Hey there, I am using Breezemite on Arch Linux with KDE Plasma 5 and when I change the bordersize to something other than `small` (in my case `no borders`) there is a small gap between the window and the side of my screen when aligning the window.
![image](https://user-images.githubusercontent.com/10999017/34272585-19da0230-e691-11e7-8330-de3bccd122a2.png)

Maybe not that much of a problem but really disturbing for someone like me :sweat_smile:

**Comment by andreyorst** [comment]
Yes, 1px transparent border. Check [this](https://github.com/andreyorst/Breezemite/issues/2#issuecomment-279088346) comment for explanations.
TL;DR:
Aurorae is quite old engine, and it can't provide zero width draggable borders, so the workaround was to set it to smallest value. There is new theme made with modern QML engine (Breeze is built upon it): [SierraBreeze](https://github.com/ishovkun/SierraBreeze).

**Comment by re1** [comment]
Worked both for me, thanks
