### ISSUE TITLE
Title bar too small fix

### ISSUE THREAD

**Issue by francoisboom23** [andreyorst/Breezemite#19]
Hi
A recent bug that i found on my desktop but not on my laptop:
The title bar is a touch too small.
![image](https://user-images.githubusercontent.com/36674414/38260598-50d0b3ec-3768-11e8-9c9d-bb6ba1ffe33f.png)

Fix: borderleft and borderright set to 3
![image](https://user-images.githubusercontent.com/36674414/38260664-86cd258e-3768-11e8-9865-2663787abd09.png)
![image](https://user-images.githubusercontent.com/36674414/38260700-9e8a87fc-3768-11e8-85fe-072fadc66399.png)

![image](https://user-images.githubusercontent.com/36674414/38260496-0b532cf0-3768-11e8-8b2f-4d1746718e04.png)

Bye

**Comment by andreyorst** [comment]
I assume that you're using a HiDPI display, or font scaling, since theese two are main reasons  of this bug. So you provided a fix for your particular setup, not for everyone.
