### ISSUE TITLE
No application menu button on title bar

### ISSUE THREAD

**Issue by idmresettrial** [andreyorst/Breezemite#3]
Hi @andreyorst,
Why when I use your theme Breezemite, the application menu button doesn't show on the title bar? It still shows normally with the theme Breeze.

**Comment by andreyorst** [comment]
@idmresettrial, aurorae doesn't support this button yet. And breeze theme is written in C++ so it is not aurorae theme, thats why this button shows only in Breeze.

**Comment by idmresettrial** [comment]
Thank you @andreyorst, I've got it.

BTW, I feel Breeze running faster, being more lightweight than any aurorae theme I've tried include Breezemite. Maybe due to aurorae engine. Could you consider writting Breezemite in C++ like Breeze?
 Your Breezemite is very nice, but it would be much better if it could run fast, be lightweight as Breeze.

**Comment by andreyorst** [comment]
@idmresettrial, i wanted to, but didn't found any understandable explanation how to write themes for plasma. And i don't have any spare time rightnow, to figuring it out by myself

**Comment by idmresettrial** [comment]
@andreyorst : Thank you, again.
