### ISSUE TITLE
HiDPI Support

### ISSUE THREAD

**Issue by jarradh** [andreyorst/Breezemite#4]
Hey,

I tried Breezemite in KDE Plasma 5.9.4 with a HiDPI screen but unfortunately the button are super small , they look better when the button size is "Oversized" but the window bar is just missing, somewhat blurred

![screenshot_20170420_145714](https://cloud.githubusercontent.com/assets/2714786/25231907/e17e7ab0-25d9-11e7-9984-2cd5e2e13c1a.png)
(normal button size)

**Comment by andreyorst** [comment]
since theme's paddings, width/height etc are set in pixels i recommend you to double all the params in layout section, or even double them twice. Sorry I cant test it because i have no HiDPI screen, and don't planning to get one

**Comment by jarradh** [comment]
doubling the values worked a charm, thank-you
