### ISSUE TITLE
Header/title width bug on plasma 5.10.2

### ISSUE THREAD

**Issue by ifree92** [andreyorst/Breezemite#9]
Here is screenshot:

![screenshot](http://i.piccy.info/i9/34f428fc5788465d1398b2cb6688b177/1498487052/661590/1157363/Screenshot_20170626_172240.png)

It happens on my archlinux (latest version at moment this post) with plasma 5.10.2. Very nice theme but width on header is...

**Comment by ifree92** [comment]
And small additional screenshot with detailed illustration  of problem:

![screenshot](http://i.piccy.info/i9/49f58238b1574e2930aeaea6fea8a034/1498487457/10579/1157363/Screenshot_20170626_173013.png)

**Comment by ifree92** [comment]
And small refinement. It occurs when I disable window border (I don't like borders...). When I use "normal" window's border size - it's ok, but around the window appears blured transparent borders (of course :D). Please fix header width with setting without border.
Thanks.

**Comment by ifree92** [comment]
And more additions: the root of problem (personally for me) is in DPI. When I set DPI less than 96 (for my 24" monitor with 1920x1080 resolution) - theme is corrupt (as I show on screenshot upper). If I set 96 DPI (and more) - it's ok.

**Comment by andreyorst** [comment]
Could you please specify which DPI you are using? I could tweak brezmiterc to match your DPI, as a quickfix.

**Comment by ifree92** [comment]
@andreyorst 
My monitor is 24" with 1920x1080 resolution.
92 DPI uses by default for my monitor.
Now as a quick fix I manually set 96 DPI and it fixed the problem.
![screenshot](http://i.imgur.com/aXD1zwg.png)
But of course some fonts looks better if I'm using native DPI.

**Comment by andreyorst** [comment]
Ok, so I'll tweak this theme according to 92 DPI and attach the file here

**Comment by ifree92** [comment]
@andreyorst thank you. Will be glad.

**Comment by andreyorst** [comment]
@ifree92 sorry for the delay, was too busy with moving to another house. Remove ".txt" from filename and replace your original rc file with this one. Should be fine. 
[Breezemiterc.txt](https://github.com/andreyorst/Breezemite/files/1117004/Breezemiterc.txt)

**Comment by L4TTiCe** [comment]
How do you make these changes ? I'm trying to fix the same issue as I'm using custom dpi on a non HiDPI display to make things small. My current DPI setting is 72. How do i calculate those values in yje Breezemiterc file?

**Comment by andreyorst** [comment]
Please specify what is your resolution.

As for value calculation - it is done by picking it step by step until it fits. Sorry for that
